### ISSUE TITLE
problem: docker container will auto stop if you run this without '-it' arguments

### ISSUE THREAD

**Issue by SpencerYang148** [teambit/bit-docker#7]
# problem about  '-it' arguments:
### 1. use this command will auto stop after server started
```
 docker run --name my-scope -p 3000:3000 harmony-scope
```
> then print logs and auto stop
> ```
> Bit server has started on port 3000
> ```

### 2. but if you add '-it' args, it works
```
 docker run -it --name my-scope -p 3000:3000 harmony-scope
```
> then print logs, it works
> ```
> Bit server is running on http://localhost:3000
> ```

## How to solve this problem?

**Comment by samirmajen** [comment]
Try adding this to your deployment spec:

```
spec: 
  containers: 
    - name: test 
      stdin: true 
      tty: true 
```
